import Head from "next/head";
import { useRouter } from "next/router";

export const Header = (): JSX.Element => {
  const router = useRouter();

  const handleNavigation = (path: string = "/") => router.push(path);

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <div className="absolute z-[3] w-full">
          <div className="container p-6 flex justify-between items-center m-auto">
            <div className="font-bold text-2xl sm:text-3xl text-white">
              <a
                role="button"
                className=" cursor-pointer"
                onClick={() => handleNavigation("/")}
              >
                TresOlas
              </a>
            </div>
            <div className="flex flex-1 justify-end">
              <nav>
                <ul className="flex gap-3">
                  <li className=" text-xl text-white p-3">
                    <a
                      role="button"
                      className=" cursor-pointer"
                      onClick={() => handleNavigation("/besurf")}
                    >
                      Besurf
                    </a>
                  </li>
                  <li className=" text-xl text-white p-3">
                    <a
                      role="button"
                      className=" cursor-pointer"
                      onClick={() => handleNavigation("/octopus")}
                    >
                      Octopus
                    </a>
                  </li>
                </ul>
              </nav>
            </div>
          </div>
        </div>
      </header>
    </>
  );
};
