import Head from "next/head";
import Image from "next/image";

export const BesurfPage = (): JSX.Element => {
  return (
    <>
      <Head>
        <title>BESurf</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative">
        <div className="relative flex flex-col m-auto z-[2] text-center h-screen justify-center bg-[url('/assets/images/besurf/banner-2.jpg')] bg-no-repeat bg-center bg-cover">
          <div className="absolute w-full h-screen bg-black z-[1] opacity-25" />
          <div className="z-[2]">
            <div className=" text-center h-[250px] sm:max-w-[575px] relative w-full sm:max-h-[360px] sm:h-[360px] m-auto">
              <Image
                src="/assets/images/besurf/besurf_logo.png"
                alt="besurf logo"
                layout="fill"
              />
            </div>

            <h2 className="text-3xl sm:text-5xl text-white font-thin">
              Surfing nunca habia sido tan divertido
            </h2>
          </div>
        </div>
      </div>
      <section className="container max-w-[1512] m-auto">
        <div>
          <div className="py-16 flex flex-col lg:flex-row gap-3.5 p-3">
            <div className="flex flex-col w-full lg:w-2/4 justify-center text-[#818181] gap-10">
              <div className=" flex flex-col gap-5">
                <h2 className="text-2xl mb-3 text-[#02685F]">
                  Experimente los descansos perfectos
                </h2>
                <p className="text-lg">
                  Sumérjase en el agua por primera vez y practique remo,
                  apareciendo y montando en indulgente descanso en la playa de
                  Bejuco. Los surfistas más experimentados pueden perfeccionar
                  sus habilidades navegando junto a un instructor experto,
                  aprendiendo a leer las olas de última hora y mejorando la
                  técnica y la forma. Los usuarios de todos los niveles de
                  habilidad pueden tomar el sol en la costa del Pacífico y
                  disfrutar de la seguridad de una experimentada escuela de surf
                  que hace énfasis en la seguridad y la diversión.
                </p>
                <ul className="flex flex-col list-disc p-6 text-lg gap-5">
                  <li>
                    Experiencia única Perfecto para todas las edades y niveles
                    de destreza.
                  </li>
                  <li>
                    Varias salidas durante el día Reciba consejos útiles de un
                    habitante de la zona
                  </li>
                  <li>Todo el equipo necesario incluido Guía</li>
                </ul>
              </div>

              <div>
                <p className="pb-5 text-xl">
                  <b className="text-[#02685F]">¿Qué haremos?</b>
                </p>
                <p className="pb-2 text-lg">
                  Comenzamos con una charla amena del océano, de nuestra
                  posición en la tabla, técnicas para poder surfear y sobre todo
                  estar seguros en el agua. Me gustaría enseñar como puedes
                  mejorar sobre la tabla. En esta zona hay olas secretas que me
                  gustaría mostrar.
                </p>
              </div>
              <div>
                <p className="pb-5 text-xl">
                  <b className="text-[#02685F]">Clases con Propósito</b>
                </p>
                <p className="text-lg">
                  Creemos en que el deporte es un precursor para alejar a
                  jóvenes de las drogas por medio del deporte enseñamos valores
                  como la disciplina la pasión, perseverancia, los creadores de
                  este contenido damos clases voluntarias a joves de la zona y
                  empleamos a chicos como instructores para asi fortalecer un
                  valor mas, el trabajo.
                </p>
              </div>
            </div>
            <div className="w-full lg:w-2/4 m-auto max-h-[856]">
              <div className="pb-3">
                <div className="w-full bg-[url('/assets/images/besurf/image-1.jpg')] bg-no-repeat bg-center bg-cover h-[447px]" />
              </div>
              <div className="flex gap-3 h-[393px]">
                <div className="w-full bg-[url('/assets/images/besurf/image-3.jpg')] bg-no-repeat bg-center bg-cover " />
                <div className="w-full bg-[url('/assets/images/besurf/image-2.jpg')] bg-no-repeat bg-center bg-cover " />
              </div>
            </div>
          </div>
        </div>
        <div></div>
      </section>
      <section className=" bg-[#FBFBFB]">
        <div className="container max-w-[1512] m-auto py-16 p-3">
          <div className="w-full text-center mb-11">
            <h2 className="text-[#02685F] text-4xl">
              <b>Nuestros Paquetes</b>
            </h2>
          </div>

          <div className="flex flex-col lg:flex-row justify-between items-center lg:items-start gap-4">
            <div className=" flex flex-col p-5 bg-white max-w-md w-full rounded-md  justify-between m-auto sm:m-0 shadow-md h-[544px]">
              <div className="flex flex-row justify-between items-center mb-5">
                <h3 className=" font-semibold text-xl text-[#02685F] mb-3">
                  Paquete Básico
                </h3>
                <p className=" font-semibold text-[40px] text-[#81B5B1] mb-3">
                  $60
                </p>
              </div>
              <div className="mb-5">
                <div className=" w-full bg-[url('/assets/images/besurf/image-3.jpg')] bg-no-repeat bg-center bg-cover h-52 rounded" />
              </div>
              <div className="mb-5 h-20">
                <p className="text-[#818181]">Paquete basico de un sesion </p>
              </div>
              <div className="flex flex-row justify-center">
                <a
                  href="#book"
                  className=" bg-[#02685F] w-56 rounded p-3 text-center text-white text-lg uppercase"
                >
                  Reserva
                </a>
              </div>
            </div>
            <div className=" flex flex-col p-5 bg-white max-w-md w-full rounded-md justify-between m-auto sm:m-0 shadow-md h-[544px]">
              <div className="flex flex-row justify-between items-center mb-5">
                <h3 className=" font-semibold text-xl text-[#02685F] mb-3">
                  Paquete 10k Puntarenas
                </h3>
                <p className=" font-semibold text-[40px] text-[#81B5B1] mb-3">
                  $80
                </p>
              </div>
              <div className="mb-5">
                <div className=" w-full bg-[url('/assets/images/besurf/image-3.jpg')] bg-no-repeat bg-center bg-cover h-52 rounded" />
              </div>
              <div className="mb-5 h-20">
                <p className="text-[#818181]">
                  Trasporte 10km alrededor de Playa Bejuco Puntarenas.
                </p>
              </div>
              <div className="flex flex-row justify-center">
                <a
                  href="#book"
                  className=" bg-[#02685F] w-56 rounded p-3 text-center text-white text-lg uppercase"
                >
                  Reserva
                </a>
              </div>
            </div>
            <div className=" flex flex-col p-5 bg-white max-w-md w-full rounded-md justify-between m-auto sm:m-0 shadow-md h-[544px]">
              <div className="flex flex-row justify-between items-center mb-5">
                <h3 className=" font-semibold text-xl text-[#02685F] mb-3">
                  Paquete Premium
                </h3>
                <p className=" font-semibold text-[40px] text-[#81B5B1] mb-3">
                  $400
                </p>
              </div>
              <div className="mb-5">
                <div className=" w-full bg-[url('/assets/images/besurf/image-3.jpg')] bg-no-repeat bg-center bg-cover h-52 rounded" />
              </div>
              <div className=" mb-5 px-5">
                <ul className="text-[#818181] list-disc flex flex-col gap-2">
                  <li>Trasporte Aeropuerto</li>
                  <li>Clases de Surf </li>
                  <li>Hospedaje</li>
                </ul>
              </div>
              <div className="flex flex-row justify-center">
                <a
                  href="#book"
                  className=" bg-[#02685F] w-56 rounded p-3 text-center text-white text-lg uppercase"
                >
                  Reserva
                </a>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section>
        <div className="py-32 flex flex-col md:flex-row gap-6 p-3  max-w-5xl mx-auto ">
          <div className="w-2/4 sm:w-1/4 m-auto ">
            <Image
              src="/assets/images/roberto.jpg"
              layout="responsive"
              alt="Roberto instructor"
              width={594}
              height={594}
              className="rounded-full"
            />
          </div>
          <div className="flex flex-col w-full md:w-3/4 justify-center ">
            <h2 className="text-[#02685F] text-4xl mb-5 text-center sm:text-start">
              <b>Conoce a Roberto nuestro instructor</b>
            </h2>
            <p className="text-[#818181]">
              Hola soy Roberto, un deportista desde el 96, he nadado en muchos
              lugares en CR y el mundo. He surfeado en diferentes países y soy
              un local que busca olas y lugares seguros y divertidos. Con 27
              años de experiencia en el océano, soy la persona indicada, experta
              para que puedas disfrutar y estar seguro.
            </p>
          </div>
        </div>
      </section>
      <section id="book" className="bg-[#02685F]">
        <div className="flex flex-col md:flex-row container max-w-[1512] m-auto py-16 p-5 ">
          <div className="flex flex-col w-full md:w-3/4 justify-center text-white">
            <h2 className="font-bold text-4xl mb-11">¿Como Reservar?</h2>
            <p className="pb-2">
              Por cuestiones del clima y oleaje es mejor contactar al instrutor
              para hacer reservaciones.
            </p>
            <p className="pb-2">
              Email: <span className="font-bold">besurfcr@gmail.com</span>
            </p>
            <p className="pb-2">
              Whatsapp: <a href="tel:88506373">+506 8850-6373</a>
            </p>
          </div>
        </div>
      </section>
    </>
  );
};
