import Head from "next/head";
import Image from "next/image";

export const HomePage = (): JSX.Element => {
  return (
    <>
      <Head>
        <title>BESurf</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <div className="absolute z-[3]">
          <div className="container p-6">
            <div className="font-bold text-2xl sm:text-3xl text-white">
              BESurf
            </div>
          </div>
        </div>
      </header>
      <div className="relative">
        <div className="relative flex flex-col m-auto z-[2] text-center h-screen justify-center bg-[url('/assets/images/banner.jpg')] bg-no-repeat bg-center bg-cover">
          <div className="absolute w-full h-screen bg-black z-[1] opacity-25" />
          <div className="z-[2]">
            <h1 className="font-bold text-4xl sm:text-6xl mb-5 text-white">
              Bejuco Surf
            </h1>
            <h2 className="text-xl sm:text-3xl text-white font-thin">
              Surfing never has been this fun
            </h2>
          </div>
        </div>
      </div>
      <section className="container max-w-5xl mx-auto">
        <div>
          <div className="py-8 flex flex-col md:flex-row gap-3.5 p-3">
            <div className="flex flex-col w-full md:w-3/4 justify-center ">
              <h2 className="text-2xl mb-3"> Lorem ipsum </h2>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla
                vitae orci odio. Duis sed magna nec lacus laoreet vehicula. In
                sed massa ut dolor lobortis cursus sit amet tempus leo. Nullam
                vulputate id odio sit amet varius. Donec justo magna, tristique
                eu gravida id, maximus ut erat. Cras nec porta purus. Maecenas
                vel efficitur nulla. Aliquam tempor sem mauris, eget tempus
                turpis scelerisque nec. Fusce id tellus at ante vestibulum
                porttitor. Phasellus efficitur rutrum vestibulum. Fusce metus
                felis, efficitur eget eros eu, luctus luctus lacus. Pellentesque
                rutrum dictum lorem, sed ornare ex rhoncus sit amet. Nulla
                facilisi. Donec vitae diam sit amet dolor consequat imperdiet.
                Maecenas bibendum ullamcorper eleifend. Pellentesque nec augue
                eget ligula scelerisque pharetra. Pellentesque a lorem mattis,
                accumsan lectus nec, accumsan sapien. Proin vitae libero quam.
              </p>
            </div>
            <div className="w-1/4 m-auto">
              <Image
                src="/assets/images/surfTable.png"
                layout="responsive"
                alt="Surfing table"
                width={1405}
                height={5000}
              />
            </div>
          </div>
        </div>
        <div></div>
      </section>
      <section className=" bg-teal-500">
        <div className="container max-w-5xl mx-auto">
          <div className="flex flex-col sm:flex-row justify-between py-8">
            <div className=" flex flex-col p-10 bg-white max-w-xs w-full rounded h-full m-auto mb-3">
              <h3 className=" font-semibold text-lg mb-3">Name</h3>
              <p className=" font-semibold text-2xl mb-3">$40</p>
              <p>Descripcion</p>
            </div>
            <div className=" flex flex-col p-10 bg-white max-w-xs w-full rounded h-full m-auto mb-3">
              <h3 className=" font-semibold text-lg mb-3">Name</h3>
              <p className=" font-semibold text-2xl mb-3">$40</p>
              <p>Descripcion</p>
            </div>
            <div className=" flex flex-col p-10 bg-white max-w-xs w-full rounded h-full m-auto">
              <h3 className=" font-semibold text-lg mb-3">Name</h3>
              <p className=" font-semibold text-2xl mb-3">$40</p>
              <p>Descripcion</p>
            </div>
          </div>
        </div>
      </section>
      <section className="">
        <div className=" p-3">
          <div className=" flex flex-col">
            <div className="flex gap-3">
              <div className="w-full">
                <Image
                  src="/assets/images/gallery/gallery-1.jpg"
                  alt="Surf lessons image 1"
                  layout="responsive"
                  width={4160}
                  height={6240}
                />
              </div>
              <div className="w-full">
                <Image
                  src="/assets/images/gallery/gallery-2.jpg"
                  alt="Surf lessons image 2"
                  layout="responsive"
                  width={4160}
                  height={6240}
                />
              </div>
            </div>
            <div className="w-full py-3">
              <Image
                src="/assets/images/gallery/gallery-3.jpg"
                alt="Surf lessons image 3"
                layout="responsive"
                width={6240}
                height={4160}
              />
            </div>
            <div className="flex gap-3">
              <div className="w-full">
                <Image
                  src="/assets/images/gallery/gallery-4.jpg"
                  alt="Surf lessons image 4"
                  layout="responsive"
                  width={3896}
                  height={5844}
                />
              </div>
              <div className="w-full">
                <Image
                  src="/assets/images/gallery/gallery-5.jpg"
                  alt="Surf lessons image 5"
                  layout="responsive"
                  width={4160}
                  height={6240}
                />
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className=" bg-teal-500 h-12"></section>
    </>
  );
};
